.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandARDrone3PictureSettingsAutoWhiteBalanceSelectionListener;
.super Ljava/lang/Object;
.source "ARCommandARDrone3PictureSettingsAutoWhiteBalanceSelectionListener.java"


# virtual methods
.method public abstract onARDrone3PictureSettingsAutoWhiteBalanceSelectionUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_PICTURESETTINGS_AUTOWHITEBALANCESELECTION_TYPE_ENUM;)V
.end method
