.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandARDrone3PictureSettingsVideoStabilizationModeListener;
.super Ljava/lang/Object;
.source "ARCommandARDrone3PictureSettingsVideoStabilizationModeListener.java"


# virtual methods
.method public abstract onARDrone3PictureSettingsVideoStabilizationModeUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_PICTURESETTINGS_VIDEOSTABILIZATIONMODE_MODE_ENUM;)V
.end method
