.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandPowerupMediaRecordStatePictureStateChangedV2Listener;
.super Ljava/lang/Object;
.source "ARCommandPowerupMediaRecordStatePictureStateChangedV2Listener.java"


# virtual methods
.method public abstract onPowerupMediaRecordStatePictureStateChangedV2Update(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_POWERUP_MEDIARECORDSTATE_PICTURESTATECHANGEDV2_STATE_ENUM;Lcom/parrot/arsdk/arcommands/ARCOMMANDS_POWERUP_MEDIARECORDSTATE_PICTURESTATECHANGEDV2_ERROR_ENUM;)V
.end method
