.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandARDrone3PictureSettingsPictureFormatSelectionListener;
.super Ljava/lang/Object;
.source "ARCommandARDrone3PictureSettingsPictureFormatSelectionListener.java"


# virtual methods
.method public abstract onARDrone3PictureSettingsPictureFormatSelectionUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_PICTURESETTINGS_PICTUREFORMATSELECTION_TYPE_ENUM;)V
.end method
