.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandPowerupMediaRecordEventVideoEventChangedListener;
.super Ljava/lang/Object;
.source "ARCommandPowerupMediaRecordEventVideoEventChangedListener.java"


# virtual methods
.method public abstract onPowerupMediaRecordEventVideoEventChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_POWERUP_MEDIARECORDEVENT_VIDEOEVENTCHANGED_EVENT_ENUM;Lcom/parrot/arsdk/arcommands/ARCOMMANDS_POWERUP_MEDIARECORDEVENT_VIDEOEVENTCHANGED_ERROR_ENUM;)V
.end method
