.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandPowerupMediaStreamingStateVideoEnableChangedListener;
.super Ljava/lang/Object;
.source "ARCommandPowerupMediaStreamingStateVideoEnableChangedListener.java"


# virtual methods
.method public abstract onPowerupMediaStreamingStateVideoEnableChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_POWERUP_MEDIASTREAMINGSTATE_VIDEOENABLECHANGED_ENABLED_ENUM;)V
.end method
