.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandARDrone3NetworkSettingsWifiSelectionListener;
.super Ljava/lang/Object;
.source "ARCommandARDrone3NetworkSettingsWifiSelectionListener.java"


# virtual methods
.method public abstract onARDrone3NetworkSettingsWifiSelectionUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_NETWORKSETTINGS_WIFISELECTION_TYPE_ENUM;Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_NETWORKSETTINGS_WIFISELECTION_BAND_ENUM;B)V
.end method
