.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandARDrone3PilotingStateNavigateHomeStateChangedListener;
.super Ljava/lang/Object;
.source "ARCommandARDrone3PilotingStateNavigateHomeStateChangedListener.java"


# virtual methods
.method public abstract onARDrone3PilotingStateNavigateHomeStateChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_PILOTINGSTATE_NAVIGATEHOMESTATECHANGED_STATE_ENUM;Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_PILOTINGSTATE_NAVIGATEHOMESTATECHANGED_REASON_ENUM;)V
.end method
