.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandCommonAccessoryStateAccessoryConfigChangedListener;
.super Ljava/lang/Object;
.source "ARCommandCommonAccessoryStateAccessoryConfigChangedListener.java"


# virtual methods
.method public abstract onCommonAccessoryStateAccessoryConfigChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_COMMON_ACCESSORYSTATE_ACCESSORYCONFIGCHANGED_NEWACCESSORY_ENUM;Lcom/parrot/arsdk/arcommands/ARCOMMANDS_COMMON_ACCESSORYSTATE_ACCESSORYCONFIGCHANGED_ERROR_ENUM;)V
.end method
