.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandJumpingSumoAnimationsStateJumpMotorProblemChangedListener;
.super Ljava/lang/Object;
.source "ARCommandJumpingSumoAnimationsStateJumpMotorProblemChangedListener.java"


# virtual methods
.method public abstract onJumpingSumoAnimationsStateJumpMotorProblemChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_JUMPINGSUMO_ANIMATIONSSTATE_JUMPMOTORPROBLEMCHANGED_ERROR_ENUM;)V
.end method
