.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandARDrone3NetworkSettingsStateWifiSelectionChangedListener;
.super Ljava/lang/Object;
.source "ARCommandARDrone3NetworkSettingsStateWifiSelectionChangedListener.java"


# virtual methods
.method public abstract onARDrone3NetworkSettingsStateWifiSelectionChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_NETWORKSETTINGSSTATE_WIFISELECTIONCHANGED_TYPE_ENUM;Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_NETWORKSETTINGSSTATE_WIFISELECTIONCHANGED_BAND_ENUM;B)V
.end method
