.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandARDrone3PictureSettingsStateVideoFramerateChangedListener;
.super Ljava/lang/Object;
.source "ARCommandARDrone3PictureSettingsStateVideoFramerateChangedListener.java"


# virtual methods
.method public abstract onARDrone3PictureSettingsStateVideoFramerateChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_PICTURESETTINGSSTATE_VIDEOFRAMERATECHANGED_FRAMERATE_ENUM;)V
.end method
