.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandARDrone3PilotingSettingsStateAutonomousFlightMaxVerticalSpeedListener;
.super Ljava/lang/Object;
.source "ARCommandARDrone3PilotingSettingsStateAutonomousFlightMaxVerticalSpeedListener.java"


# virtual methods
.method public abstract onARDrone3PilotingSettingsStateAutonomousFlightMaxVerticalSpeedUpdate(F)V
.end method
