.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandJumpingSumoMediaRecordStateVideoStateChangedV2Listener;
.super Ljava/lang/Object;
.source "ARCommandJumpingSumoMediaRecordStateVideoStateChangedV2Listener.java"


# virtual methods
.method public abstract onJumpingSumoMediaRecordStateVideoStateChangedV2Update(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_JUMPINGSUMO_MEDIARECORDSTATE_VIDEOSTATECHANGEDV2_STATE_ENUM;Lcom/parrot/arsdk/arcommands/ARCOMMANDS_JUMPINGSUMO_MEDIARECORDSTATE_VIDEOSTATECHANGEDV2_ERROR_ENUM;)V
.end method
