.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandJumpingSumoMediaRecordStateVideoStateChangedListener;
.super Ljava/lang/Object;
.source "ARCommandJumpingSumoMediaRecordStateVideoStateChangedListener.java"


# virtual methods
.method public abstract onJumpingSumoMediaRecordStateVideoStateChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_JUMPINGSUMO_MEDIARECORDSTATE_VIDEOSTATECHANGED_STATE_ENUM;B)V
.end method
