.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandARDrone3PilotingSettingsStateCirclingDirectionChangedListener;
.super Ljava/lang/Object;
.source "ARCommandARDrone3PilotingSettingsStateCirclingDirectionChangedListener.java"


# virtual methods
.method public abstract onARDrone3PilotingSettingsStateCirclingDirectionChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_PILOTINGSETTINGSSTATE_CIRCLINGDIRECTIONCHANGED_VALUE_ENUM;)V
.end method
