.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandARDrone3SettingsStateMotorErrorLastErrorChangedListener;
.super Ljava/lang/Object;
.source "ARCommandARDrone3SettingsStateMotorErrorLastErrorChangedListener.java"


# virtual methods
.method public abstract onARDrone3SettingsStateMotorErrorLastErrorChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_SETTINGSSTATE_MOTORERRORLASTERRORCHANGED_MOTORERROR_ENUM;)V
.end method
