.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandARDrone3PictureSettingsStateVideoResolutionsChangedListener;
.super Ljava/lang/Object;
.source "ARCommandARDrone3PictureSettingsStateVideoResolutionsChangedListener.java"


# virtual methods
.method public abstract onARDrone3PictureSettingsStateVideoResolutionsChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_PICTURESETTINGSSTATE_VIDEORESOLUTIONSCHANGED_TYPE_ENUM;)V
.end method
