.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandJumpingSumoRoadPlanStateScriptDeleteChangedListener;
.super Ljava/lang/Object;
.source "ARCommandJumpingSumoRoadPlanStateScriptDeleteChangedListener.java"


# virtual methods
.method public abstract onJumpingSumoRoadPlanStateScriptDeleteChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_JUMPINGSUMO_ROADPLANSTATE_SCRIPTDELETECHANGED_RESULTCODE_ENUM;)V
.end method
