.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandMiniDroneMediaRecordStatePictureStateChangedV2Listener;
.super Ljava/lang/Object;
.source "ARCommandMiniDroneMediaRecordStatePictureStateChangedV2Listener.java"


# virtual methods
.method public abstract onMiniDroneMediaRecordStatePictureStateChangedV2Update(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_MINIDRONE_MEDIARECORDSTATE_PICTURESTATECHANGEDV2_STATE_ENUM;Lcom/parrot/arsdk/arcommands/ARCOMMANDS_MINIDRONE_MEDIARECORDSTATE_PICTURESTATECHANGEDV2_ERROR_ENUM;)V
.end method
