.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandARDrone3MediaRecordStateVideoStateChangedV2Listener;
.super Ljava/lang/Object;
.source "ARCommandARDrone3MediaRecordStateVideoStateChangedV2Listener.java"


# virtual methods
.method public abstract onARDrone3MediaRecordStateVideoStateChangedV2Update(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_MEDIARECORDSTATE_VIDEOSTATECHANGEDV2_STATE_ENUM;Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_MEDIARECORDSTATE_VIDEOSTATECHANGEDV2_ERROR_ENUM;)V
.end method
