.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandSkyControllerSettingsStateProductVariantChangedListener;
.super Ljava/lang/Object;
.source "ARCommandSkyControllerSettingsStateProductVariantChangedListener.java"


# virtual methods
.method public abstract onSkyControllerSettingsStateProductVariantChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_SKYCONTROLLER_SETTINGSSTATE_PRODUCTVARIANTCHANGED_VARIANT_ENUM;)V
.end method
