.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandARDrone3AntiflickeringStateElectricFrequencyChangedListener;
.super Ljava/lang/Object;
.source "ARCommandARDrone3AntiflickeringStateElectricFrequencyChangedListener.java"


# virtual methods
.method public abstract onARDrone3AntiflickeringStateElectricFrequencyChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_ANTIFLICKERINGSTATE_ELECTRICFREQUENCYCHANGED_FREQUENCY_ENUM;)V
.end method
