.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandSkyControllerCalibrationStateMagnetoCalibrationStateListener;
.super Ljava/lang/Object;
.source "ARCommandSkyControllerCalibrationStateMagnetoCalibrationStateListener.java"


# virtual methods
.method public abstract onSkyControllerCalibrationStateMagnetoCalibrationStateUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_SKYCONTROLLER_CALIBRATIONSTATE_MAGNETOCALIBRATIONSTATE_STATUS_ENUM;BBB)V
.end method
