.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandSkyControllerAccessPointSettingsStateAccessPointChannelChangedListener;
.super Ljava/lang/Object;
.source "ARCommandSkyControllerAccessPointSettingsStateAccessPointChannelChangedListener.java"


# virtual methods
.method public abstract onSkyControllerAccessPointSettingsStateAccessPointChannelChangedUpdate(B)V
.end method
