.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandARDrone3NetworkSettingsStateWifiSecurityChangedListener;
.super Ljava/lang/Object;
.source "ARCommandARDrone3NetworkSettingsStateWifiSecurityChangedListener.java"


# virtual methods
.method public abstract onARDrone3NetworkSettingsStateWifiSecurityChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_NETWORKSETTINGSSTATE_WIFISECURITYCHANGED_TYPE_ENUM;)V
.end method
