.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandJumpingSumoNetworkSettingsStateWifiSelectionChangedListener;
.super Ljava/lang/Object;
.source "ARCommandJumpingSumoNetworkSettingsStateWifiSelectionChangedListener.java"


# virtual methods
.method public abstract onJumpingSumoNetworkSettingsStateWifiSelectionChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_JUMPINGSUMO_NETWORKSETTINGSSTATE_WIFISELECTIONCHANGED_TYPE_ENUM;Lcom/parrot/arsdk/arcommands/ARCOMMANDS_JUMPINGSUMO_NETWORKSETTINGSSTATE_WIFISELECTIONCHANGED_BAND_ENUM;B)V
.end method
