.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandARDrone3NetworkSettingsStateWifiSecurityListener;
.super Ljava/lang/Object;
.source "ARCommandARDrone3NetworkSettingsStateWifiSecurityListener.java"


# virtual methods
.method public abstract onARDrone3NetworkSettingsStateWifiSecurityUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_NETWORKSETTINGSSTATE_WIFISECURITY_TYPE_ENUM;Ljava/lang/String;Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_NETWORKSETTINGSSTATE_WIFISECURITY_KEYTYPE_ENUM;)V
.end method
