.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandARDrone3MediaStreamingStateVideoEnableChangedListener;
.super Ljava/lang/Object;
.source "ARCommandARDrone3MediaStreamingStateVideoEnableChangedListener.java"


# virtual methods
.method public abstract onARDrone3MediaStreamingStateVideoEnableChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_ARDRONE3_MEDIASTREAMINGSTATE_VIDEOENABLECHANGED_ENABLED_ENUM;)V
.end method
