.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandJumpingSumoMediaRecordStatePictureStateChangedV2Listener;
.super Ljava/lang/Object;
.source "ARCommandJumpingSumoMediaRecordStatePictureStateChangedV2Listener.java"


# virtual methods
.method public abstract onJumpingSumoMediaRecordStatePictureStateChangedV2Update(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_JUMPINGSUMO_MEDIARECORDSTATE_PICTURESTATECHANGEDV2_STATE_ENUM;Lcom/parrot/arsdk/arcommands/ARCOMMANDS_JUMPINGSUMO_MEDIARECORDSTATE_PICTURESTATECHANGEDV2_ERROR_ENUM;)V
.end method
