.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandARDrone3PilotingSettingsStateAutonomousFlightMaxVerticalAccelerationListener;
.super Ljava/lang/Object;
.source "ARCommandARDrone3PilotingSettingsStateAutonomousFlightMaxVerticalAccelerationListener.java"


# virtual methods
.method public abstract onARDrone3PilotingSettingsStateAutonomousFlightMaxVerticalAccelerationUpdate(F)V
.end method
